Sprint 2
ClevertecFrontendLab/viktechsolutions pull request #2
Opened 2024-02-26 19:08 UTC by viktechsolutions

2024-02-26 19:13 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 1.
Количество непройденных тестов: 1.

2024-02-26 19:17 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 1.
Количество непройденных тестов: 1.

2024-02-27 10:06 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 7.
Количество непройденных тестов: 0.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709028367/reg-success-2.png)

2024-02-27 10:59 UTC, Pred1993 commented
![Снимок экрана 2024-02-27 135837](https://github.com/ClevertecFrontendLab/viktechsolutions/assets/103571130/7b34a487-7d8c-476c-89da-8a9773119643)
Не та жирность и дочка выходит из контейнера

2024-02-27 11:01 UTC, Pred1993 commented
![Снимок экрана 2024-02-27 140030](https://github.com/ClevertecFrontendLab/viktechsolutions/assets/103571130/d47aea21-2069-4435-8fd7-aafdf7d28056)
Не тот цвет и где текст-подсказка, на восстановлении пароля также

2024-02-27 11:05 UTC, Pred1993 requested changes
исправляй UI

2024-02-27 12:43 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 7.
Количество непройденных тестов: 0.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709037794/reg-success-2.png)

2024-02-27 12:51 UTC, Pred1993 requested changes
нет скринов некоторых

2024-02-27 12:52 UTC, viktechsolutions commented
где взять их?
я ж не делаю их

2024-02-27 13:43 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 7.
Количество непройденных тестов: 0.
***
**change-pass-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-error-1.png)
***
**change-pass-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-error-2.png)
***
**change-pass-error-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-error-3.png)
***
**change-pass-error-4.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-error-4.png)
***
**change-pass-error-5.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-error-5.png)
***
**change-pass-error-6.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-error-6.png)
***
**change-pass-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-success-1.png)
***
**change-pass-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-success-2.png)
***
**change-pass-success-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/change-pass-success-3.png)
***
**login-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/login-error-1.png)
***
**login-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/login-error-2.png)
***
**login-remember-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/login-remember-1.png)
***
**login-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/login-success-1.png)
***
**reg-error-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/reg-error-1.png)
***
**reg-error-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/reg-error-2.png)
***
**reg-success-1.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/reg-success-1.png)
***
**reg-success-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/viktechsolutions/1709041391/reg-success-2.png)

2024-02-27 14:34 UTC, Pred1993 approved these changes

2024-02-27 15:42 UTC, VitalyHanchar approved these changes

2024-02-27 15:43 UTC, merged